### ISSUE TITLE
求一份vuesri的文档

### ISSUE THREAD

**Issue by peshje8023** [EralChen/simple-ssr#1]
你好，你是vuesri的作者吧，我是一个arcgis的初学者。vuesri的在线文档已经打不开了。有没有离线版的？万分感谢

**Comment by EralChen** [comment]
@peshje8023 你好，感谢你的关注。`vuesri` 是我在公司这几年间，根据实际项目对 arcgis 封装的结果。实际上，我们公司已经从 `vuesri`  迁移到了我另一个 `@vuesri/core` 中。很意外也很惊喜，你在茫茫类库中找到它。目前它只是一个内源的库。如果你想尝试它 ，添加我的微信做交流：
![187f341b96e9202cc3cdae9e026a9e8](https://github.com/EralChen/simple-ssr/assets/82485978/4cd784d1-effd-4a38-8da3-cd557cfbde50)
